vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        article_image:
            uri_prefix: /medias/articles
            upload_destination: '%kernel.project_dir%/public/medias/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
